# Generated by Django 4.2.7 on 2024-01-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certipy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='path',
            new_name='fields',
        ),
        migrations.AddField(
            model_name='template',
            name='file',
            field=models.FileField(default='', upload_to='templates/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
